# Dog.create!(name: "Fido", age: 10, details: "Lovable guy currently being fostered by a family with kids, love cats, looking for forever home", image: "bassett.jpg", user_id: 6)
#  Dog.create!(name: "Shasta", age: 7, details: "Love Lap sitting and face licking, currently residing at Austin Animal Shelter", image: "shitzu.webp", user_id: 6) 
#  Dog.create!(name: "Bernie", age: 3, details: "Love Lap sitting and face licking, currently residing at Austin Animal Shelter", image: "dog.png", user_id: 6)
#  Dog.create!(name: "Fred", age: 6, details: "Lovable guy currently being fostered by a family with kids, love cats, looking for forever home", image: "dachshund.jpg", user_id: 6)
#  Dog.create!(name: "Bruno", age: 1, details: "Love Lap sitting and face licking, currently residing at Austin Animal Shelter", image: "goldenretriever.png", user_id: 6)
#  Dog.create!(name: "Spot", age: 8, details: "Love Lap sitting and face licking, currently residing at Austin Animal Shelter", image: "dogdaterfix.jpg", user_id: 6)


 Interest.create!(name: "fetch")
 Interest.create!(name: "running")
 Interest.create!(name: "digging")
 Interest.create!(name: "licking")
 Interest.create!(name: "tricks")
 Interest.create!(name: "eating")
 Interest.create!(name: "treats")
 Interest.create!(name: "hunting")
 Interest.create!(name: "sitting")
 Interest.create!(name: "cuddling")
 Interest.create!(name: "walks")
 Interest.create!(name: "napping")
 Interest.create!(name: "car rides")
 Interest.create!(name: "tug-o-war")
 Interest.create!(name: "toys")

 